### ISSUE TITLE
Version was not updated in ext_emconf.php and latest versions not uploaded to TER (TYPO3 Extension repository)

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#109]
Latest release is [2.3.0.](https://github.com/web-vision/wv_deepltranslate/releases/tag/2.3.0) But the version number in ext_emconf.php is 2.2.2. 

Also, the latest versions (2.2.2 and 2.3.0) have not been published on TER: https://extensions.typo3.org/extension/wv_deepltranslate

(However, I would wait with that until #108 is solved).

The version is more relevant for non-Composer installations, but is also displayed in Extension Manager for Composer installation.

Personally, I would recommend the following (part of this is best practice, but not everything always applied):

* create TER version simultaneously with tagging a version for Packagist and automate this (using [EXT:tailor](https://packagist.org/packages/typo3/tailor)). Some extension do this using a GitHub CI pipeline, e.g. https://github.com/TYPO3-Documentation/tea/blob/main/.github/workflows/publish.yml
* create an explicit commit to bump up a version, e.g. change version, apply commit: commit -m "v2.3.0";git tag "v2.3.0"
* (this is not usually followed, but I find it helpful): after incrementing the version, change the version to something with -dev until the next version is applied, e.g. 

ext_emconf.php
`'version' => '2.4.0-dev'`

git add .;git commit -m "v2.4.0-dev"

I find it helpful, to add a commit statement to increment only the version numbers. This makes it easier to follow in the commit history, what came after the latest release.

**Comment by calien666** [comment]
Will close this for now, as we fixed it in latest release.
