### ISSUE TITLE
Make copy modes working

### ISSUE THREAD

**Issue by tieupmedia** [web-vision/wv_deepltranslate#11]
The translation modes should work with copies, too. Sure, first automatic translation is done 1:1, but it should be possible to add custom elements to translated pages, too.

In my opinion this missing is a major circumstance and it should have been mentioned in the README.md

**Comment by NairCoder** [comment]
At the moment, updated readme.md with a message that copy is not affected with the API data.
We wanted to keep the copy function out of translation for the user. Otherwise, both options will be identical in purpose, right?
Thanks for your comment.
