### ISSUE TITLE
Translation no longer works with latest master / problem with language codes EN-GB / EN-US with using "en" as iso code

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#112]
The extension no longer translates on my site using the latest master. 

The reason might be related to how the languages are fetched in TranslateHook and how the 2 letter iso code (e.g. "en")  is used to compare with supported languages which may contain 2-2 letter code ("EN-GB") .

see also: supported languages:

In the supported languages which are fetched from DeepL there are both language codes, the 2 letter iso codes (e.g. DA) and for example "EN-GB".

https://www.deepl.com/docs-api/general/get-languages/

-----

`TranslateHook::processTranslateTo_copyAction`

```
// this results in 'en'
$targetLanguageIso = $targetLanguage->getTwoLetterIsoCode();
// but  $this->deeplService->apiSupportedLanguages) contains "EN-GB" and "EN-US", but not "EN"
$langSupportedByDeepLApi = in_array(strtoupper($targetLanguageIso), $this->deeplService->apiSupportedLanguages);

// this would translate using the wrong target language "en", instead of e.g. "EN-GB"
$response = $this->deeplService->translateRequest($content, $targetLanguageIso, $sourceLanguageIso);
```

In my installation `$langSupportedByDeepLApi` is false and `translateRequest` is not called (for source language German and target language English).

It might be better to get the mapping from the `SettingsRepository` based on the language uid, not use the 2 letter iso code (but use a fallback as well, in case this is not configured).

## versions

* wv_deepltranslate, latest master
* TYPO3 v 11.5.22

languages:

- 0 - default (German)
- 1 - English
etc.

Settings 

```
 select * from tx_deepl_settings;
+-----+-----+------------------------------------------------------------------------------------------------------+------------+--------+-----------+---------+---------+
| uid | pid | languages_assigned                                                                                   | crdate     | tstamp | cruser_id | deleted | sorting |
+-----+-----+------------------------------------------------------------------------------------------------------+------------+--------+-----------+---------+---------+
|   1 |   0 | a:7:{i:1;s:5:"EN-GB";i:2;s:2:"NL";i:3;s:2:"RU";i:4;s:2:"PL";i:5;s:2:"ES";i:6;s:2:"AR";i:7;s:2:"TR";} | 1623133012 |      0 |         0 |       0 |       0 |
+-----+-----+------------------------------------------------------------------------------------------------------+------------+--------+-----------+---------+---------+

```

**Comment by sypets** [comment]
$targetLanguageMapping is already corrrectly assigned and could be used, but this is not really used later on:

```
$targetLanguageMapping = $this->deeplSettingsRepository->getMappings($targetLanguage['uid']);
if ($targetLanguageMapping !== null) {
                    $targetLanguage['language_isocode'] = $targetLanguageMapping;
 }
// ...
// overwritten later
$targetLanguage = $site->getLanguageById($languageRecord['uid']);

```

**Comment by sypets** [comment]
quick hack fixes it for me (but I am not sure if that covers all use cases).:

line 137:```

$targetCode = strtoupper($targetLanguageMapping ?: $targetLanguageIso);
$langSupportedByDeepLApi = in_array($targetCode, $this->deeplService->apiSupportedLanguages);
if ($langSupportedByDeepLApi) {
                    $response = $this->deeplService->translateRequest($content, $targetCode, $sourceLanguageIso);
```

**Comment by Patta** [comment]
I can confirm, that with version 2.3.1, the translation from default language DE to EN-GB is not working. EN-GB is set in settings module. EN works.

**Comment by baschny** [comment]
Same here, Fix from @sypets seems to "temporarily solve the issue", but this whole part of the code is a "mess" and difficult to understand, so I hope the original devs can take a look at it and make a stable fix.

**Comment by calien666** [comment]
@baschny
We are working on it, because your'e right.
