### ISSUE TITLE
Fetching language information via DB table sys_language is deprecated (is used in TranslateHook)

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#113]
The language information is fetched from sys_language DB table in` TranslateHook::processTranslateTo_copyAction`. The site configuration is also used, but as a fallback later in the function.

(This is also makes it a bit error prone and difficult to maintain because there are several if / else branches which depend on if the sys_language table is filled.)

It is recommended to **not** fetch the languages from sys_language DB tables, but use the site configuration (at least for TYPO3 v11). In fact the sys_language table is deprecated.

> Adapt your code to always use site languages for fetching and processing language related information.
> Since the introduction of site handling back in TYPO3 v9, available languages and their associated information, for example locale, ISO code or the navigation title are configured in the site configurations. As a consequence, the sys_language table just duplicated this information and is therefore now deprecated.
> The Core internally does not longer rely on this table but fetches necessary information from the site languages instead. This means, there won't be any relation to the sys_language table, which allows to define any kind of "ID" for the languageField field of records, which is usually sys_language_uid.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html

See also:

* https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/SiteHandling/AccessingSiteConfiguration.html#finding-a-site-object
* https://github.com/typo3/typo3/blob/11.5/typo3/sysext/core/Classes/Site/Entity/SiteLanguage.php

I saw you still support TYPO3 v9, it should be safe to changes this for v9 also (since the site configuration was introduced in TYPO3 v9).

https://github.com/web-vision/wv_deepltranslate/blob/07cb50b8c78e19becd0861ae3756abb020472775/Classes/Hooks/TranslateHook.php#L66

**Comment by calien666** [comment]
Hi @sypets,
we're working on it, as we know about this. as you see in the pr #121, we will refactor to usage of only SiteConfiguration.
