### ISSUE TITLE
Feature request: Make it possible to configure the glossary name

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#114]
Currently, the glossary name is constructed by

```
$glossaryNamePrefix = 'DeepL';
$glossaryName = $glossaryNamePrefix . '-' . strtoupper($sourceLang) . '-' . strtoupper($targetLang);
```

Effectively, you cannot control the glossary name. If you test the glossary on a test system, you might unintentionally overwrite the glossary on the production system.

**Comment by calien666** [comment]
Hi @sypets,

According to !119 with this feature it would be possible, to add own external glossaries. I guess, this is the intention of your issue? If so, I'll take it to the team.

Regards,
Markus

**Comment by sypets** [comment]
@calien666 Thank you. Making the glossary name configurable is also useful not only if the functionality is moved to a separate extension.

If changing the glossary entries on a development or test systems, you may want to not unintentionally overwrite the main glossary. So, I think it would be useful to make the glossary name configurable in any case via Extension Configuration. You can still use the current name as default.
