### ISSUE TITLE
Translation of news > links does not work

### ISSUE THREAD

**Issue by baschny** [web-vision/wv_deepltranslate#115]
We want "auto-translation" for news records, and this works just fine:
```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['bodytext']['l10n_mode'] = 'prefixLangTitle';
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['teaser']['l10n_mode'] = 'prefixLangTitle';
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['title']['l10n_mode'] = 'prefixLangTitle';
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['subtitle']['l10n_mode'] = 'prefixLangTitle';
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['alternative_title']['l10n_mode'] = 'prefixLangTitle';
...
```

But every news has a field of `related_links` which is an `inline` relation to another table. I tried this:
```
$GLOBALS['TCA']['tx_news_domain_model_link']['columns']['description']['l10n_mode'] = 'prefixLangTitle';
$GLOBALS['TCA']['tx_news_domain_model_link']['columns']['title']['l10n_mode'] = 'prefixLangTitle';
```

All news fields are translated, but not the related link title / description. Is there any trick to make it work, or is it just a bug (or missing feature)?

**Comment by calien666** [comment]
Hi @baschny,

I tried to figure out the problem and found a solution for you.

The setting, which doesn't allow translation is the behaviour in config. So just drop this in your TCA/Overrides and localisation will work:

```php
$linkColumns = [
        'title',
        'description'
    ];
    foreach ($linkColumns as $column) {
        unset($GLOBALS['TCA']['tx_news_domain_model_link']['columns'][$column]['config']['behaviour']['allowLanguageSynchronization']);
        $GLOBALS['TCA']['tx_news_domain_model_link']['columns'][$column]['l10n_mode']
            = 'prefixLangTitle';
    }
```

**Comment by baschny** [comment]
It works, thanks.

**Comment by calien666** [comment]
I tried some parts and figured out, why these fields are translated by DeepL, but not written to database. I figured out, this could be handled with a simple DataHandler Hook. PR #138 will bring a solution without disabling allowLanguageSynchronization
