### ISSUE TITLE
Synchronising of glossary does not work, glossary is not used (and it is not documented how it should work)

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#117]
I think this might have worked before, because otherwise #99 would not have occurred. Also, the list command shows several glossaries (which is also not correct because there should not be several), the latest of them was January 13, 2023.). For further tests, I deleted the already existing glossaries on DeepL so that can't be the reason this is not working anymore.

I have debugged the code while creating glossary entries and they are never synchronized (entries in tx_wvdeepltranslate_domain_model_glossariessync are not created and glossary is not created on DeepL) and it seems obvious it cannot work, at least not in v11.

I set a breakpoint in DataHandlerHook::prepareLangagues, DataHandlerHook::processDatamap_afterDatabaseOperations and GlossarySyncController::update, DeeplGlossaryService::createGlossary

In order to synchronized glossaries, a hook is used: DataHandlerHook::processDatamap_afterDatabaseOperations.

If the following is true, it returns and does nothing

* `if ($status !== 'update') {`
* `if (!isset($fieldArray['l10n_parent']) || $fieldArray['l10n_parent'] === 0) {`

When debugging this, it always returns because `l10n_parent` is not set.

When TYPO3 calls this hook, it does not pass the full field array, it passes only the changed values, see core DataHandler, before calling processDatamap_afterDatabaseOperations:

 $fieldArray = $this->compareFieldArrayWithCurrentAndUnset($table, $id, $fieldArray);

Unfortunately, the hook is not well documented.

Also, I do not think it is a good idea to sync 

## Versions

* TYPO3 11.5.22
* wv_deepltranslate: latest master with patch for #112

## current list of glossaries

The (undocumented) command shows:

```
php vendor/bin/typo3 wv_deepltranslate:glossary_list
============
Read more here: https://www.deepl.com/docs-api/managing-glossaries/listing-glossaries/
============
+--------------------------------------+-------------+-------+-------------+-------------+-----------------------------+-------------+
| glossary_id                          | name        | ready | source_lang | target_lang | creation_time               | entry_count |
+--------------------------------------+-------------+-------+-------------+-------------+-----------------------------+-------------+
| fd9d3e36-b49b-46ab-bf4e-6e496ec86f8b | DeepL-DE-EN | 1     | de          | en          | 2023-01-13T14:23:05.777668Z | 1           |
| 7f6012e5-f92d-42c8-ad47-16bc31ae0fe3 | DeepL-DE-EN | 1     | de          | en          | 2023-01-13T15:16:51.6142Z   | 1           |
| 82f145f2-3b0c-405f-a4c7-a798f44ac080 | DeepL-DE-EN | 1     | de          | en          | 2022-08-09T07:00:04.146722Z | 1           |
| 4cd291f9-059c-4d11-a0b2-a0f6befd9f72 | DeepL-DE-EN | 1     | de          | en          | 2022-08-09T07:00:21.947595Z | 1           |
| b3b071ae-c715-4503-ae8c-fd14f124e1dc | DeepL-DE-EN | 1     | de          | en          | 2022-08-09T07:11:25.170876Z | 1           |
| 1064e7a0-d0a0-4635-aaa0-0d21ccc423ad | DeepL-DE-EN | 1     | de          | en          | 2022-08-09T07:11:41.074742Z | 1           |
| ae9c3db9-c53c-4b80-a48c-52d0e16e9a2c | DeepL-DE-EN | 1     | de          | en          | 2022-08-15T13:08:00.366722Z | 1           |
| 358faacf-9c69-466a-aa73-8163c0d00ca2 | DeepL-DE-EN | 1     | de          | en          | 2022-08-15T13:08:10.57717Z  | 2           |
| 21721f2c-2812-46cb-8555-29deb4c9ea0c | DeepL-DE-EN | 1     | de          | en          | 2022-08-15T13:08:58.83386Z  | 2           |
+--------------------------------------+-------------+-------+-------------+-------------+-----------------------------+-------------+

```

Probably during previous tests, these were created.

After deleting them, no new glossaries are uploaded to DeepL, even after creating new glossary entries and translating something. 

None of the breakpoints mentioned above are reached, except for DataHandlerHook::processDatamap_afterDatabaseOperations where the function is left right away because l10n_parent is not set. Also, no entrie in tx_wvdeepltranslate_domain_model_glossariessync are created.

```
php vendor/bin/typo3 wv_deepltranslate:glossary_cleanup
php vendor/bin/typo3 wv_deepltranslate:glossary_list
============
No Glossaries found.
Read more here: https://www.deepl.com/docs-api/managing-glossaries/listing-glossaries/
============

```

```
select count(*) from  tx_wvdeepltranslate_domain_model_glossariessync;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

**Comment by LimeUwe** [comment]
We found that since version 2.3.1 the glossary sync is not working anymore. 
In 2.2.1 it still works.

**Comment by datango** [comment]
```
This works for me:

index 0a65d7d..3e789b4 100644
--- a/Classes/Hooks/DataHandlerHook.php
+++ b/Classes/Hooks/DataHandlerHook.php
@@ -96,10 +96,12 @@ class DataHandlerHook implements LoggerAwareInterface
             return;
         }

-        if (!isset($fieldArray['l10n_parent']) || $fieldArray['l10n_parent'] === 0) {
+        $currentRecord = BackendUtility::getRecord($table, $id);
+
+        if (!isset($currentRecord['l10n_parent']) || $currentRecord['l10n_parent'] === 0) {
             return;
         }
-

```

**Comment by sypets** [comment]
@datango That should probably work. Can you create a PR?

What I find weird is that is seems to have worked previously. (There are some minor changes there by me but that was due to a PHP 8.1 bug)

Probably best to fix this too to make it more readable. 

`- if (!isset($currentRecord['l10n_parent']) || $currentRecord['l10n_parent'] === 0) {
`

But should also check the use of the types (I am not sure if getRecords would really return int for this or not string. So comparing with 0 without casting may not be the best idea).


This should work though:

`+ if (!($currentRecord['l10n_parent'] ?? false)) {`

(Would be easier to create a PR and test and review that)

**Comment by sypets** [comment]
As explained in https://github.com/web-vision/wv_deepltranslate/pull/135#issuecomment-1438271154, hold the PRs.
