### ISSUE TITLE
Please move glossary functionality to separate extension

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#119]
This has several advantages:

* more flexibility. It could be possible to create a glossary elsewhere (which might be the case if dedicated software is used for this). In this extension, only the glossary name could be configured and how the glossary entries are created and uploaded can be handled with whatever option is deemed most useful.
* more stability in this extension. Since the glossary functionality was added, several bugs were introduced
* separation of concerns
* it is possible to use drop-in replacement for glossary functionality

In practice, translation and handling of glossaries may be used by several applications and several departments in an organisation. Handling it in a TYPO3 extension may not always be the first choice. For example, in our organisation, the glossary was maintained in a translation program and then exported.

**Comment by calien666** [comment]
@sypets We have discussed your issue several times and have come to a decision that we hope will work for you.
The basic glossary functionality, as introduced in v2.2.0 and (mostly) fixed, will remain in the current extension.
In addition, we will provide the ability to register external glossaries with an API where you can write your own extension to handle the glossary. This will even help here: https://github.com/web-vision/wv_deepltranslate/pull/60#issuecomment-1483111841

**Comment by calien666** [comment]
As no reaction on this issue, I will close here. Feel free to open a new one, if you think, this might be wrong.
