### ISSUE TITLE
`403 Forbidden` response on apiUrl without access

### ISSUE THREAD

**Issue by helsner** [web-vision/wv_deepltranslate#124]
Hi, thanks for the nice extension!
I'm wondering on one point i stumbled upon a few times now.
When no valid apiUrl with proper access is set there is an error thrown that blocks the whole rendering of the page module, which i don't understand.
It is good and easy to see the issue then, but at the same time the whole BE becomes not usable regarding content administration.

The affected code segment is within DeeplService.php line 162 and below.
to be precise the issue is the `exit` call within the catch. 
IMHO this should be replaced with a simple `return [];` to prevent a total breakdown.

This would prevent overall issues regarding the GET request. 
I'm thinking of the following cases that could happen:
1. not yet existing api credentials, but a dev preps the integratio
2. outdated or changed credentials
3. the API not being accessible due to internal network regulation
4. the API not being accessible due to outages on their side.

**Comment by calien666** [comment]
Bug is accepted. #134 will fix this, too.

**Comment by helsner** [comment]
Super cool! thanks a lot for the quick action
only thing needed now is a release :D Is there anything, that i can help you with, to make this possible?

**Comment by calien666** [comment]
Currently there is only Glossary and Documentation. If you want to join Docs, take a look at my pull request
