### ISSUE TITLE
Add extension-key to composer.json

### ISSUE THREAD

**Issue by spoonerWeb** [web-vision/wv_deepltranslate#13]
On every composer command with installed extension there comes this error:

```The TYPO3 extension package "web-vision/wv_deepltranslate", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)```

This is the mentioned report. 😉

**Comment by sypets** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#minimal-composer-json
