### ISSUE TITLE
[TASK] Use typo3/testing-framework

### ISSUE THREAD

**Issue by calien666** [web-vision/wv_deepltranslate#144]
After nimut/testing-framework is abandoned, switch to typo3/testing-framework

- [x] change framework
- [x] rewrite tests
- [x] Prepare TF for TYPO3 v12

**Comment by sbuerk** [comment]
What is meant with "rewrite tests" ?

**Comment by calien666** [comment]
> @calien666 What is meant with point `rewrite tests` ?

Test rewriting for fitting on TYPO3 TF, that's the only point here

**Comment by sbuerk** [comment]
> > @calien666 What is meant with point `rewrite tests` ?
> 
> Test rewriting for fitting on TYPO3 TF, that's the only point here

Thanks for makeing this clear.. So exactly what I have done in the PR.
