### ISSUE TITLE
Glossary-Sync: Error on duplicate Entry

### ISSUE THREAD

**Issue by lausberg-ac** [web-vision/wv_deepltranslate#159]
If there is a duplicate source in the Glossary the syncronisation gives an Error:

(1/1) #400 GuzzleHttp\Exception\ClientException
Client error: `POST https://api.deepl.com/v2/glossaries` resulted in a `400 Bad Request` response: {"message":"Invalid glossary entries provided","detail":"Key with the index 252 (starting at position 11121) duplicates (truncated...)

It would be nice to find duplicates before Glossary-Sync.

**Comment by calien666** [comment]
Hi @lausberg-ac,
Thank xou for using this ext and for your test. As you describe, this issue shouldn't happen. We will fix it asap and it will there in next release.
