### ISSUE TITLE
PageTS tab label is overwritten

### ISSUE THREAD

**Issue by LimeUwe** [web-vision/wv_deepltranslate#168]
Version: current dev-master

In page settings the label of the PageTS tabl ist overwritten with the label "DeepL Translation"

![Bildschirmfoto_2023-03-10_um_09_27_21](https://user-images.githubusercontent.com/8911618/224263984-ab8402fc-4c11-4a0b-8ea0-e2b9cffdce9a.jpg)

**Comment by Schwuuuuup** [comment]
I can confirm this, some elements shift from "Ressources" to "DeepL" tab
