### ISSUE TITLE
[BUG] Standard localize mode skips choose language step

### ISSUE THREAD

**Issue by philip-hartmann** [web-vision/wv_deepltranslate#177]
**Describe the bug**
The default localize mode from TYPO3 skips the choose language mode step if this extension is installed.

**To Reproduce**
- have at least 3 languages configured in your site config
- translate a page
- translate the same page for a different language with the default localize mode from TYPO3 (skips choose language step)

**Expected behavior**
Do not skip the choose language step if multiple languages are avaible.

**TYPO3 Setup**
* TYPO3 version: 11.5.23
* wv_deepltranslate version: 2.2.1 || 2.3.1 || dev-v3.x-dev

**Additional context**
The function getUsedLanguagesInPage does not return all available languages. There are some parts missing which are present in the default LocalizationController.

**Comment by calien666** [comment]
Closed by #178 
Thank you for contributing.
