### ISSUE TITLE
[BUG] afterDatabaseOperations failing on glossaries, resulting in no sync

### ISSUE THREAD

**Issue by devgass** [web-vision/wv_deepltranslate#179]
**Description**
`WebVision\WvDeepltranslate\Hooks\DataHandlerHook->processDatamap_afterDatabaseOperations()` uses the parameter `$fieldArray` which contains the modified fields of the records. In order for the method to proceed and create a synced glossary, `$fieldArray['l10n_parent']` has to be set. But that field is rarely ever changed when creating and editing target language terms, so the method is stopped early. This results in missing glossary syncs that then can't be used for translations.

**Reproduce**
- Create and save a glossary entry over "List" module
- localize it using the "Localize to" buttons
- edit term only
- **= no sync created**

**Setup**
* TYPO3 11.5.26
* nginx
* MariaDB
* PHP 8.1
* DeepL paid API
* composer setup

**Comment by calien666** [comment]
@devgass Sorry for responding so late. One question to you: Which version of DeepL translate did you use? 2.3.1 or dev-master?

**Comment by calien666** [comment]
Description leads to version 2.3.
As we currently don't have automatic sync with DeepL, there couldn't be an automatic sync. With release 3.0, a sync button appears in glossary modules, which will do the job.

**Comment by calien666** [comment]
@devgass Is the issue still existing?

**Comment by calien666** [comment]
As no reaction on this issue, I will close here. Feel free to open a new one, if you think, this might be wrong.
