### ISSUE TITLE
TER version 1.1.2 contains __MACOSX folder

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#20]
There is no real harm and it just contains some backup files but this is a bad practice smell - can be avoided by using  `.gitattributes`, see 

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

and then using the "git archive" method for creating the archive.

Or better still, integrate the current way to automatically upload extension to TER.

**Comment by sypets** [comment]
See also "[Publish an extension](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/PublishExtension/Index.html)" and the **recently added** [Publish your extension in the TER](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/PublishExtension/PublishToTER/Index.html#publish-to-ter) with the section  https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/PublishExtension/PublishToTER/Index.html#how-to-publish-an-extension

to use `TYPO3/tailor` and add the uploading to your CI.

**Comment by borishinzer** [comment]
Fixed in release 2.0.1
