### ISSUE TITLE
[BUG] Creating translation of page using the "Page" module fails with error message

### ISSUE THREAD

**Issue by Stuffy** [web-vision/wv_deepltranslate#206]
When trying to translate a page using the "Page" module, an error occurs during step 1 of the translation process. The error message is `Please complete missing deepl configurations.` .

**To Reproduce**
Create "Sites"-Configuration, and create a few content elements on a page with content that you want to have translated.
Using the "Page"-Module, try to translate said content elements using the translation-wizard. This will fail with the error message mentioned above.

**Expected behavior**
The translation wizard should progress to the next step and allow translation of the content.

**Screenshots**
![wv_deepltranslate_issue](https://github.com/web-vision/wv_deepltranslate/assets/2758171/d97a7413-8c79-4d1e-b609-b991d7e3e183)

**TYPO3 Setup**
* TYPO3 Version: 11.5.27
* Server: Apache
* Database type and version: MySQL 8.0.25
* PHP version:  7.4.33 
* DeepL free or paid API?: Both result in the same error
* composer or classic setup? composer

**Comment by Stuffy** [comment]
#207

**Comment by georgschurkin** [comment]
I have the same problem with TYPO3 9. By the way, the translation in the "List" module works pretty well.

**Comment by bigahuna** [comment]
Same problem here. It seams that the extension setting (apiKey) is not available inside  "Page" module translations
