### ISSUE TITLE
Support for deepl  formality option

### ISSUE THREAD

**Issue by Megafry** [web-vision/wv_deepltranslate#21]
Thank you for this great Extension.
My client asked me if i can set the option "formality" to "more". [API-Doc](https://www.deepl.com/de/docs-api/translating-text/#request)

Unfortunately there are no settings for this, you can add this in the next version?

**Comment by ayacoo** [comment]
@Megafry Could you give us some feedback about this patch?

Is it clear enough where to set the settings? Does the patch work for you or your client?

**Comment by ayacoo** [comment]
Hint: PR #33 is the right one :-)

**Comment by NairCoder** [comment]
Hello @Megafry 
Since the option is added into master [v2.0.0](https://github.com/web-vision/wv_deepltranslate/tree/2.0.0), closing the issue now.
A shoutout to @ayacoo. Thanks for your support. 👍

**Comment by Megafry** [comment]
Hello @NairCoder and @ayacoo 
Works like a charm, thank you for the work
