### ISSUE TITLE
[TASK] Register required JavaScript other way

### ISSUE THREAD

**Issue by calien666** [web-vision/wv_deepltranslate#222]
**Describe the task**
As of deprecation of the TYPO3_MODE constant (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html), the registration of Backend JavaScript should be optimised.

**Expected behavior**
Register JavaScript in the proper way: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Feature-90899-IntroduceAssetPreRenderingEvents.html

**Comment by sbuerk** [comment]
Please correct me, but we are talking here about a generic
Backend JavaScript module, without a concrete BE module or
controller. Right ?

The mentioned event is a generic one, which is fired in BE
and FE mode. Sure, this can be done and used. However, I'd
like to suggest an alternative:

* `TYPO3 v11`: `renderPreProcess` or `renderPostProcess` hook
* `TYPO3 v12`: `\TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent`

This really emphasizes that we are only dealing within BE context.
Additionally, this would keep the "transistion" clean. We can provide
the HOOK and the event in parallel. With v11 the hook is used, and
with v12 the event. No overlapping between both, and no version
check needed.

:link: [Gerrit Patch 74797](https://review.typo3.org/c/Packages/TYPO3.CMS/+/74797)
:link: [Changelog Hook Removed v12](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97451-RemoveBackendControllerPageHooks.html)
:link: [Changelog added Event](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97451-PSR-14EventsForBackendPageController.html)

**Comment by sbuerk** [comment]
Reconsidert it. The best way is to use the PageRenderer `render-preProcess` hook instead.
The core itself transformed with that replacement.
