### ISSUE TITLE
[BUG] Translation without glossary not possible

### ISSUE THREAD

**Issue by calien666** [web-vision/wv_deepltranslate#232]
**Describe the bug**
Without a glossary set, TYPO3 returns a type error.

**To Reproduce**
* Clean TYPO3 install
* No glossary defined
* Translate page
* error thrown

**Expected behavior**
Translation without glossary is done

**Screenshots**
![Screenshot 2023-05-15 at 11 42 09](https://github.com/web-vision/wv_deepltranslate/assets/11405116/8613968c-311e-422e-8b8d-2e0731bbc276)

**TYPO3 Setup**
* TYPO3 Version: 11.5
* PHP version: 8.2
* DeepL free or paid API?: Paid
* composer or classic setup?: composer

**Comment by borishinzer** [comment]
Problem only exists, if I chose the "Translate with DeepL" Button in the page module. As a workaround I created an alternative language, the traditional ways. But this resulted in pages settings (title) not being translated with DeepL. After the alternative language was existing, i was able to translate page content with DeepL without issues.

**Comment by calien666** [comment]
Closed by #235
