### ISSUE TITLE
[BUG] Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

### ISSUE THREAD

**Issue by lausberg-ac** [web-vision/wv_deepltranslate#234]
**Describe the bug**
In _wv_deepltranslate/Classes/Utility/DeeplBackendUtility.php line 260 fetchAssociative is called. This does not work with PHP 7.4.

**To Reproduce**
Install wv_deepltranslate on Typo3 10.4 with php7.4 and klick on the PageView

**Expected behavior**
Content is shown

**Screenshots**
![grafik](https://github.com/web-vision/wv_deepltranslate/assets/95365147/24f9df9e-bfde-4b86-936e-9bf81fbf24b5)

**TYPO3 Setup**
* TYPO3 Version 10.4.37
* Server (nginx-fpm)
* Database: mariaDB 10.6.12
* PHP version: 7.4.33
* DeepL paid API
* classic setup

**Additional context**
Solution is: replace fetchAssociative() in Line 260 in DeeplBackendUtility.php by fetch()

Same Fault in DeeplRecordListController.php Line 105

**Comment by calien666** [comment]
Thank you for reporting this issue. We will release a fixed version asap.
