### ISSUE TITLE
[BUG] Glossary not used (second try)

### ISSUE THREAD

**Issue by lausberg-ac** [web-vision/wv_deepltranslate#238]
**Describe the bug**
The Glossary is not used.

**To Reproduce**
Create a funny Glossary-Entry and translate text with that word in Page View.

**Expected behavior**
Glossary used

**Error and possible Solution**
In Classes/Utility/DeeplBackendUtility.php Line 362 the QueryParams are used. The Code looks for Id, but in my Array the correct Index is pageId. Maybe in Typo3 11 the Index has changed. I tested on 10.

**TYPO3 Setup**
* TYPO3 Version 10.4.37
* Server NginX
* Database: MariaDB 10.6.12
* PHP: 7.4.33
* DeepL paid API
* classic setup

**Comment by calien666** [comment]
After debugging the issue appears, if translated via Translation Wizard. Translation in list module works as expected.
