### ISSUE TITLE
[BUG] Access to undefined array keys for translations in list view

### ISSUE THREAD

**Issue by bigahuna** [web-vision/wv_deepltranslate#239]
**Describe the bug**
Access to undefined array keys

`PHP Warning: Undefined array key "glossary_id" in /var/www/html/public/typo3conf/ext/wv_deepltranslate/Classes/Service/DeeplService.php line 82`

`PHP Warning: Undefined array key "l10n_mode" in /var/www/html/public/typo3conf/ext/wv_deepltranslate/Classes/Hooks/AllowLanguageSynchronizationHook.php line 34`

**To Reproduce**
Try to translate a custom entry (i.e. a blog post or a category) inside the list view (web view works fine)

If an exception is thrown or an error occurs, the full stack trace
is also helpful to gain quick insight.

**Expected behavior**
Just translate the given entry

**TYPO3 Setup**
* 11.5.27
* apache 2.4
* mariadb 10.4.28
* 8.1.16
* DeepL paid API
* composer setup

**Comment by bigahuna** [comment]
I want to commit a bugfix to the 3.0 branch because this issue needs to be fixed there and not in main. How can I do this?

**Comment by calien666** [comment]
> I want to commit a bugfix to the 3.0 branch because this issue needs to be fixed there and not in main. How can I do this?

You are able to create a pull request to branch 3.0 from your fork.

**Comment by bigahuna** [comment]
I'm so sorry. The one who can has normally a big advantage :) Pull request is created.
