### ISSUE TITLE
[FEATURE] Hide buttons if api key isnt set (Deepl)

### ISSUE THREAD

**Issue by ayacoo** [web-vision/wv_deepltranslate#25]
At the moment, the translation buttons are always displayed and when you click on them, you get a message that the settings have to be completed.

Of course, an editor can't do much with that at first. My suggestion: Only show the buttons if the API settings exist.

**Comment by ayacoo** [comment]
Since the buttons are assembled in JavaScript, it is not so easy to get the EXT settings.

If you absolutely want to have the buttons out, you can overwrite the TranslateHook with XClass or fork the extension.

**Comment by sypets** [comment]
See also #8 and #19
