### ISSUE TITLE
[FEATURE] Updating translations for changed fields of content elements

### ISSUE THREAD

**Issue by flolanger** [web-vision/wv_deepltranslate#274]
Currently (as far as I know) it's not possible to update the translation of an already translated content element if the content of the original content element has been edited.

**Describe the solution you'd like**
It would be super convenient to have a feature where the extension checks the "dirty" (changed) fields of the original content element and updates/overwrites the translated fields accordingly. This behavior could either be enabled or disabled in the extension settings or (if possible) decided by the backend user when saving the content element.

**Additional context**
Many customers ask for this kind of feature, as other CMS can already handle such things.

**Comment by calien666** [comment]
This issue is duplicated in closed repository. For getting more information about release, feel free to contact @borishinzer

**Comment by borishinzer** [comment]
@SZChimp you can find it here: https://www.web-vision.de/en/automated-translations-with-typo3-and-deepl.html
