### ISSUE TITLE
[BUG] Fatal error DeeplRecordListController

### ISSUE THREAD

**Issue by ayacoo** [web-vision/wv_deepltranslate#275]
**Describe the bug**
`Fatal error: Declaration of WebVision\WvDeepltranslate\Override\DeeplRecordListController::languageSelector($requestUri): string must be compatible with TYPO3\CMS\Backend\Controller\RecordListController::languageSelector(array $
siteLanguages, string $requestUri): string in /var/www/html/vendor/web-vision/wv_deepltranslate/Classes/Override/DeeplRecordListController.php on line 23`

see https://github.com/TYPO3/typo3/commit/630e8cd35a63f1056b25d6077120da331325f7ab

The error comes directly after installing the dev-main and when I fire a CLI command in the console.

TYPO3 12.4.1 / wv_deepltranslate dev-main

**Comment by calien666** [comment]
We're working on a version 12 currently, but actual main is not v12 supported, even if composer.json shows this.

**Comment by calien666** [comment]
We reseted the main branch to current v3, which is NOT compatible with TYPO3 v12. If you need a v12 compat version, feel free to contact @borishinzer
