### ISSUE TITLE
Disable Google Translation for Users

### ISSUE THREAD

**Issue by notaus557** [web-vision/wv_deepltranslate#281]
Hello.,

it would be great If is possible to only allow the deepL Translation option and disable google in the localization menu. Maybe this is possible by configuration?

TiA

**Comment by calien666** [comment]
Thank you for your question. `wv_deepltranslate` version 3 is only security and bugfix release. We are working on version 4, which removes Google translate completely.
New features won't be added to version 3 anymore.
Feel free to take a look here: https://www.web-vision.de/en/automated-translations-with-typo3-and-deepl.html
