### ISSUE TITLE
TYPO3 12 compatible

### ISSUE THREAD

**Issue by matin73** [web-vision/wv_deepltranslate#284]
Are there any plans to make extension compatible with latest TYPO3?
Martin

**Comment by calien666** [comment]
Sure, version is out. But currentliy not public. Take a look here https://www.web-vision.de/en/automated-translations-with-typo3-and-deepl.html and contact @borishinzer, if you want to know, when it will be public or you need access asap.

**Comment by timdreier** [comment]
@borishinzer can you already tell when a v12 compatible version will be released? :)

**Comment by timdreier** [comment]
Hi,
I created a fork which is compatible with TYPO3 V12 :)

https://github.com/timdreier/wv_deepltranslate

I just tried to make it work somehow, to use it in my personal projects. Don’t expect it to work perfekt. I just put the minimal effort in it to make it work in my hobbyist projects.

If your rely on the extension better stick to the early access program.
