### ISSUE TITLE
Disable strict translation workflow.

### ISSUE THREAD

**Issue by o-zinger** [web-vision/wv_deepltranslate#294]
Hello

I would like to see only Deepl translation.  
How can I disable the standard translation method?

**Comment by borishinzer** [comment]
I would not recommend to disable the strict translation mode, as TYPO3 then only copies the content elements and they are no longer connected. You would loose upcoming features as the retranslate function mentioned here: https://www.web-vision.de/en/deepl-translate-for-typo3-development-outlook.html
