### ISSUE TITLE
[BUG] cURL error 28: Resolving timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by Pravin0711** [web-vision/wv_deepltranslate#295]
I am using typo3 11.5.30 and wv_deepltranslate latest version(3.0.5). it's work well few days ago.
Now, i am getting below error when i goto page module and i can't edit my page content.

![Screenshot (5)](https://github.com/web-vision/wv_deepltranslate/assets/137781747/736d479a-0cc5-4a32-a17c-5611870730a7)

can you please help me out here...

**Comment by Pravin0711** [comment]
Sorry. i think it's some server issue.

**Comment by baggyownz** [comment]
Hello Pravin0711,
what was your solution? I have the same issue in the backend at the settings module.
Thanks for your answer
