### ISSUE TITLE
[FEATURE] Translation in both directions

### ISSUE THREAD

**Issue by tschelabaumann** [web-vision/wv_deepltranslate#296]
**Is your feature request related to a problem? Please describe.**
It looks like the translation into another language is always based on the default languange of the CMS.
Means, if EN is default, then the translation feature is only show for EN contents.
But if I initially have a DE content which I want to translate into EN, then the translation feature is not shown.

**Describe the solution you'd like**
I'd like to have the translation feature available no matter which language the origin content has.

**Comment by borishinzer** [comment]
IMO this is at least no longer the case with TYPO3 version 12. Just checked it with our demo. If you ant to try on your own, feel free to register for a demo here: https://www.web-vision.de/typo3-automatische-uebersetzungen-mit-deepl.html
