### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by herzogkienast** [web-vision/wv_deepltranslate#298]
Hey guys,

With version 2.0.0 under TYPO3 V 9.5.28 the list view does not work anymore.
I get the error message because the glossary tables are missing.

Oops, an error occurred!
An exception occurred while executing 'SELECT `uid` FROM `tx_wvdeepltranslate_glossaryentry` WHERE (`tx_wvdeepltranslate_glossaryentry`.`pid` = ?) AND (`tx_wvdeepltranslate_glossaryentry`.`deleted` = 0) LIMIT 1' with params [625]: Table 'u901249_wiedenest.tx_wvdeepltranslate_glossaryentry' doesn't exist

I know this version of the extension will not work with the glossary - you told me so.

Database is up-to-date, cleared cashes and so on. Do you have any idea for me to solve this?

Cheers, Andrea

**Comment by calien666** [comment]
Hey. Are you sure using 2.0.0?
Glossary was introduced in 2.2.0. In this case version 2.0 can't have any information about glossary. Probably you installed a later version and your TCA has some cached information about the table `tx_wvdeepltranslate_glossaryentry`?

**Comment by herzogkienast** [comment]
Hey, sure, I'm using 2.0.0. But can be that I once tried to install a newer version, which did not work with the old TYPO3 and then just installed over it. 
But today I cleared all caches. Could that be my problem? Didn't look at the TCA until now.
