### ISSUE TITLE
Buttons for translation with DeepL are displayed even if target language is not supported

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#30]
## Reproduce

1. Add language "Turkish"
2. Create page with content and translation page to "Turkish" 
3. Click Translate, choose Translate (deepl)
4. an error message appears:

`Client error: `POST https://api.deepl.com/v2/translate` resulted in a `400 Bad Request` response: {"message":"Value for 'target_lang' not supported."}`

I would expect the DeepL translate button to not be displayed if the target language is not supported by DeepL.

**Comment by sypets** [comment]
Actually, the text next to the button says 

> Other languages are ignored and the normal translation function of TYPO3 is used

but this is not the case - see error message.

**Comment by AlexSanFa** [comment]
The manual says:

> Fork of deepltranslate from pitsolutions.This extension provides option to translate content elements and tca record fields to desired language(supported by Deepl). As a fallback, Google translate option is also provided as they provide support for many languages that deepl isn’t providing.

Will the bug be fixed somehow? Ask for information, when will this be done.
