### ISSUE TITLE
[FEATURE] Allow translating "sys_file_metadata"

### ISSUE THREAD

**Issue by koehnlein** [web-vision/wv_deepltranslate#304]
**Is your feature request related to a problem? Please describe.**
At the moment, the records of "sys_file_metadata" in the Files module cannot be translated with DeepL. The TYPO3 backend has alternative implementations to generate the translate buttons, which are not covered by the existing hooks of this extension. And also the records are stored outsid any Site context, which could cause additional trouble.

**Describe the solution you'd like**
It would be great, if the buttons to translate a record with DeepL would also be available near the "Create metadata" links and in the language select box for [NEW] records.

![Filelist-·-bildbuehne-·-Griffwerk-GmbH-TYPO3-CMS-11-5-31-(1)](https://github.com/web-vision/wv_deepltranslate/assets/16088567/24042f81-db5e-4bee-82fb-8f280cf4c2da)

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by borishinzer** [comment]
This is already on the roadmap for the next release: https://www.web-vision.de/en/deepl-translate-for-typo3-development-outlook.html

**Comment by borishinzer** [comment]
It's now available as *beta* for Early Access Partners as add-on.
