### ISSUE TITLE
[BUG] Page module unusable without wifi

### ISSUE THREAD

**Issue by kitzberger** [web-vision/wv_deepltranslate#305]
**Describe the bug**
The page module is only accessable with a working internet connection. 

**To Reproduce**
Sit on a train with shitty wifi and try working on your local dev environment.

```
cURL error 28: Connection timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-free.deepl.com/v2/languages?type=target
```

**Expected behavior**
Don't call remote server when API key is not set!

**Comment by baschny** [comment]
I would add to that: do not call the API at all on every backend request?!? If there is a need to know "available languages", cache that information to avoid further API calls.

**Comment by calien666** [comment]
As you can see in https://github.com/web-vision/wv_deepltranslate/blob/main/Classes/Service/DeeplService.php#L105, the available languages ARE cached. But they need to be loaded once, to get cached, as empty response is not cached, avoiding the backend to work with an empty cache with no relevant languages inside.
I don't know, if this is a bug in common, as the main case is working on a server with active internet connection.

We will discuss, if this is needed to be fixed or not. When releasing v4 as public, this issue will not occur any longer, as we use DeepL API module there, which checks the API key.

**Comment by NarkNiro** [comment]
With the EAP release, the errors are intercepted and written to the log.
This means that the backend module can also be used offline.
