### ISSUE TITLE
[BUG]: If API is down please do a fallback ....

### ISSUE THREAD

**Issue by powermix** [web-vision/wv_deepltranslate#317]
there was a point where API not reachable 503 , i could not reach typo3 backend at all.

**Comment by borishinzer** [comment]
Currently we are working on an error output, in case the API is down, limits are exceeded, etc. As we rely on the availability of DeepL API, I don't see a possibility for a fallback by now.

**Comment by NarkNiro** [comment]
Link https://github.com/web-vision/wv_deepltranslate/issues/305
