### ISSUE TITLE
[BUG] Not sure if it's a bug or a configuration issue

### ISSUE THREAD

**Issue by PaDa19** [web-vision/wv_deepltranslate#318]
Today I installed wv_deepltranslate for the first time. It's the V12 development version.
The "Translate with DeepL" dropdown for translating a page only shows up in the list view but not in the page view.
I can't translate news records because there are no deepl translate buttons in the list view.

Could you please let me know if these are:
- bugs
- features that are still missing in V12
- problems with my configuration / site

Thanks,
Patrick.

**Comment by borishinzer** [comment]
@PaDa19 , if you are referring to the EAP version, you are in the wrong repository :) But yes, we are already aware of that. Please send me an email from your company so I can check the license and I will add you then to the other repo.
