### ISSUE TITLE
Error when translating in list mode into a language not supported by Deepl 

### ISSUE THREAD

**Issue by AlexSanFa** [web-vision/wv_deepltranslate#32]
Hello!

I use wv_deepltranslate V.1.1.2 under Typo3 V.9.5. I get the following error when translating in list mode (e.g. for a news article) into a language not supported by Deepl (e.g. Czech, Russian or Turkish)

{"status":"false","message":"Client error: `POST https:\/\/api.deepl.com\/v2\/translate` resulted in a `400 Bad Request` response:\n{\"message\":\"Value for 'target_lang' not supported.\"}\n"}

Thanks for your response in advance!

**Comment by sypets** [comment]
Related to #30

**Comment by calien666** [comment]
After reworking and fine tuning a better behaviour this issue is covered my internal exception catching and doesn't appear any longer.
