### ISSUE TITLE
[BUG] Option to set api endpoint missing

### ISSUE THREAD

**Issue by criwe** [web-vision/wv_deepltranslate#333]
Option to set api is not available like described in https://docs.typo3.org/p/web-vision/wv_deepltranslate/4.3/en-us/Reference/ExtensionConfiguration/Index.html

**To Reproduce**
Follow the instructions in the documentation. You get:

![deepl](https://github.com/web-vision/wv_deepltranslate/assets/7531138/fac04ad6-737b-4859-a607-8aae49bb820e)

When using a pro key, it leads to error:  Authorization failure, check authentication key, message: Wrong endpoint. Use https://api.deepl.com (0)  (i think the free api is used)

I need to change the url in the TranslatorOptions.php 

`public const DEFAULT_SERVER_URL_FREE = 'https://api.deepl.com';`

to get it running.

**TYPO3 Setup**
* TYPO3 Version 12.4.15
* Server (Apache
* Database type and version MariaDB
* PHP version 8.2
* DeepL free or paid API?  paid
* composer or classic setup? composer

Thanks!
Christoph

**Comment by NarkNiro** [comment]
Hello @criwe ,

The API URL is no longer required with version 4.0.0. The URL is determined by the package `deeplcom/deepl-php` through the API key or user. We have therefore removed the configuration option for this.
