### ISSUE TITLE
Class "DeepL\Translator" not found

### ISSUE THREAD

**Issue by matin73** [web-vision/wv_deepltranslate#337]
Installling extension classic way via repository not working. Error:
Class "DeepL\Translator" not found

**Comment by NarkNiro** [comment]
Hallo @matin73 ,

If you want to use the extension in a TYPO3 legacy instance. You should download the extension resources from [TYPO3 TER](https://extensions.typo3.org/extension/wv_deepltranslate/).
There we upload a ZIP with the required dependencies. Which are needed for TYPO3 Legacy Install.

We recommend a TYPO3 Composer instance, where the extension dependencies are automatically loaded via Composer. TYPO3 itself also points this out.

**Comment by matin73** [comment]
.. but version in TER does not work ... elements are not translatetd at all ...

**Comment by NarkNiro** [comment]
I have created a TYPO3 legacy project, loaded the extension from TER and installed it. A **default** content element header was translated. Everything works as it should.

Are the content element fields in the TCA in your TYPO3 configured with the '10n_mode' => 'prefixLangTitle' that should be translated?
Because only then can DeepL be included in the translation process.

**Comment by sbuerk** [comment]
> .. but version in TER does not work ... elements are not translatetd at all ...

1. Do you have the DeepL API key configured in the extension configuration ?
2. Did you configured target languages in your siteconfiguration languages ?
Don't forget to clear the all caches after changing site configuration.

The installation and class not found issue could not reproduced.

**Comment by matin73** [comment]
Do you have the DeepL API key configured in the extension configuration ? YES
    Did you configured target languages in your siteconfiguration languages ? YES
    Don't forget to clear the all caches after changing site configuration. YES
