### ISSUE TITLE
[FEATURE] Pass TYPO3 proxy config to DeepL Translator

### ISSUE THREAD

**Issue by Idleworks** [web-vision/wv_deepltranslate#352]
This applies to wv_deepltranslate version 4.2.x

**Is your feature request related to a problem? Please describe.**
In some server environments you have to use a http proxy for public requests.
The common way in TYPO3 is to set HTTP|proxy option in TYPO3_CONF_VARS as documented here https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/HTTP.html#confval-globals-typo3-conf-vars-sys-http-proxy
Currently this configuration is ignored and requests get timed out which also leads to a long backend login delay.

**Describe the solution you'd like**
Pass HTTP|proxy option to Deepl\Translator

**Comment by sbuerk** [comment]
@Idleworks Thanks for the report. That have been reported already (#330) and should be fixed with merged #331. Can you test with "main" branch ifthat solves your issue already ?

**Comment by Idleworks** [comment]
@sbuerk Thank you for clarification. I had to remove paid repository from composer.json to retrieve newest updates. Seems like our paid account has expired.

**Comment by calien666** [comment]
> @sbuerk Thank you for clarification. I had to remove paid repository from composer.json to retrieve newest updates. Seems like our paid account has expired.

I don't think, your account has expired. We only develop the main extension here. So if you use other extensions from the EAP, you still need the packagist.com access, but you have to disable the main extension from packagist.com repository, as the main development now is open source for v11/v12 development and EAP development begins soon for v12/v13 support. The version 4 is maintained here and not in EAP context and the packages are currently not synced. If you want me to look up, if your payment expired, feel free to contact me via email.
