### ISSUE TITLE
[BUG] Translations of Repeating Items (Mask) are being placed in the original module

### ISSUE THREAD

**Issue by rschumachr** [web-vision/wv_deepltranslate#373]
We use multiple Mask modules containing repeating Items (IRRE) such as a Teaser module or a Logo-List module. When we edit/insert these modules on a page with the deepl extension active (set to automatically translate), some of the repeating item translations will be saved in the original language causing duplicates in the frontend at the original language and missing items for the frontend in the target language.

It doesn't happen every single time and not to every repeating item, but more often than not, causing it to be a major issue for us when inserting and updating content. We can edit the modules again and remove the faulty translations, but often times, after saving, they are being recreated again in the original language. Often times the recreated repeating items are different ones than the first time.

In general, we have not been able to observe any behavior patterns with this issue. Sometimes it works after multiple trys, other times we give up because it keeps creating translations in the wrong place. We have tried multiple different mask modules on multiple different pages (also freshly created pages without content). Mask Modules that don't contain any repeating items don't cause any problems.

The only error we occasionally get is one like this: **1: Localization failed: There already are localizations (506) for language 1 of the "tx_mask_logos" record 482** Although that mostly seems to appear after we removed the translated module and tried saving the original module to automatically create a new translation. The problem often occurs without that error showing up, though. Other times that error shows up in other modules but the translation still works.

In the screenshot you can see, the first entry being the original and the 2nd entry being the translation (identifiable by the little banner below the link field showing the original value).

<img width="874" alt="Screenshot 2024-11-20 at 4 11 25 PM" src="https://github.com/user-attachments/assets/d1edd993-9559-40de-8e14-aa6a77a62366">

**TYPO3 Setup**
* TYPO3 12.4.23 (composer setup)
* Server: Apache-cgi
* Database: MySQL
* PHP 8.2
* Mask 8.3.11
* DeepL paid API

**Comment by calien666** [comment]
Thank you for reporting. As you described a usage of deepltranslate-bulk, I moved the issue to the internal ticketing system.
