### ISSUE TITLE
Feature request: Add support for DeepL glossary

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#39]
The DeepL glossary is also supported within the API since August 24, 2021.

> The glossary functions allow you to create, inspect and delete glossaries. It is available at https://api.deepl.com/v2/glossaries. Glossaries created with the glossary function can be used in translate requests by specifying the glossary_id parameter.

This may improve the output because a more domain specific set of terms is used. For example, for the university we use a term library for English / German which is regularly updated.

---

* glossary documentation: https://www.deepl.com/docs-api/managing-glossaries/
* [Announcing Glossary Support for the DeepL API](https://www.deepl.com/en/blog/announcing-glossary-support-for-deepl-api)
* First blog entry for glossary support: https://www.deepl.com/en/blog/20200506

**Comment by borishinzer** [comment]
Seems we found some sponsors for this feature, which is very much appreciated. Thanks to the yet unmentioned sponsors.

**Comment by Riiiad** [comment]
Glossary Feature is release with version 2.2.0
