### ISSUE TITLE
TYPO3 11.5.x

### ISSUE THREAD

**Issue by matin73** [web-vision/wv_deepltranslate#42]
Hello,
is there a plan to make it compatible with latest TYPO3 11.5 version?
Thanks!
Martin

**Comment by Charanth** [comment]
There was a upgrade-v11 Branch. 
But it seems, as if there are still some issues. At least the Method _makeLocalizationPanel_ has changed in core since v11.0 
The Parameters changed and also something within the method itself.

**Comment by jwiedNic** [comment]
I'm on it right now, debugging

**Comment by borishinzer** [comment]
Released
