### ISSUE TITLE
wv_deepltranslate does not show translations.

### ISSUE THREAD

**Issue by lucasalvo** [web-vision/wv_deepltranslate#46]
Hello Community,

i installed the wv_deepltranslate extension on a Typo3 Version 10 Project.

I've already set the Deepl APi Key and the other configs.

But when i tried to translate a standard CE like Text with Picture it doesn't show the translation.

My Deepl character consumption is counting every translation.

Does somebody has any idea?

**Comment by borishinzer** [comment]
Hey, is this a large site with many content elements? Please try a smaller site first.

**Comment by lucasalvo** [comment]
Hey, i tested it with a single Content Element. 

So it doesn't matter how many Elements are on one site. 

Still won't work.

**Comment by calien666** [comment]
Sorry for answering that late, but is the issue still present in latest version? If not, I will close the ticket.

**Comment by bokazio** [comment]
Hey! Same Problem here with Version 2.3.1 in  TYPO3 V11 (PHP7.4 and PHP 8.2 in ddev container).
The "translated" CE is still stays in original language (in this case german).
I tried with the Deepl free Api. Google Translation works!

**Comment by calien666** [comment]
Can you please test, if this issue still appears in latest master version? And how did you configure your TCA for translations? (Even if I guess, it's correct, as your counter counts translations).

When problem is there in latest master, it would be helpful to get an overview of your setup, as our tests all passed without problems.

**Comment by calien666** [comment]
As no reaction on this issue, I will close here. Feel free to open a new one, if you think, this might be wrong.
