### ISSUE TITLE
Missing or wrong PHP compatibility.

### ISSUE THREAD

**Issue by datango** [web-vision/wv_deepltranslate#50]
For example, since the last version 2.0.1, code like the following is used:

`$possibleTranslations = array_map(static fn($siteLanguage) => $siteLanguage->getLanguageId(), $this->languagesAllowedForUser);
`

https://github.com/web-vision/wv_deepltranslate/blob/2.0.1/Classes/Override/DatabaseRecordList.php#L42

This is only compatible with PHP 7.4 and up.

Compatibility with PHP <=7.3 is no longer given. Please make the version compatible to PHP < 7.4 or adjust the requirements accordingly.

**Comment by NarkNiro** [comment]
It would be better to update to php version 7.4 or higher here.
