### ISSUE TITLE
Too few arguments to function makeLocalizationPanel

### ISSUE THREAD

**Issue by griesi007** [web-vision/wv_deepltranslate#51]
On TYPO3 10.4.23 with wv_deepltranslate 2.0.1 on PHP 7.4 the following error occurs in the list module on any page:
	
Oops, an error occurred!
Too few arguments to function WebVision\WvDeepltranslate\Override\DatabaseRecordList::makeLocalizationPanel(), 2 passed in /typo3/sysext/recordlist/Classes/RecordList/DatabaseRecordList.php on line 1342 and exactly 3 expected

**Comment by PeaceSfiSh** [comment]
Duplication of #48

**Comment by NarkNiro** [comment]
Was fix in Version 2.1.0 ;)
