### ISSUE TITLE
Typo3 CurlError

### ISSUE THREAD

**Issue by PowerAmbroz** [web-vision/wv_deepltranslate#52]
Hi.
I've downloaded your extension for Typo3 and when I try to translate a small media&test containing Hello World in the processing step it stops. When I refresh the page in my logs I see an error: 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: cURL error 56: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) | GuzzleHttp\Exception\RequestException thrown in file /home/user/Projects/test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php in line 201. 

The test environment is on a local machine with apache2. Curl enabled.

Best Regards.

**Comment by dmitryd** [comment]
This seems like your local issue with network connections.
