### ISSUE TITLE
require.js in Frontend

### ISSUE THREAD

**Issue by createdwithlove** [web-vision/wv_deepltranslate#54]
TYPO3 v10.4.27 with EXT:wv_deepltranslate v2.0.1
`require.js` and `requirejs-loader.js` x and y are loaded in the frontend and cause errors there.

**Comment by madces** [comment]
Same Problem

Hotfix in ext_localconf.php:

`if (defined('TYPO3_MODE') && TYPO3_MODE === 'BE') {
    //override Localization.js
    $pageRenderer = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Page\PageRenderer::class);
    $pageRenderer->loadRequireJsModule('TYPO3/CMS/WvDeepltranslate/Localization');
}`

**Comment by NarkNiro** [comment]
Hi guys,

For this error I could already create a pull request ;)
PR: #58

**Comment by dominikdoerr** [comment]
Since the fix has already been merged (thanks, @NarkNiro), I guess this issue can be closed 🙂

**Comment by NarkNiro** [comment]
Thanks, @dominikdoerr I close the ticket :)
