### ISSUE TITLE
Translation process stuck

### ISSUE THREAD

**Issue by dfpsoeew** [web-vision/wv_deepltranslate#62]
API key and URL are set, languages are configured in the extension settings. When translating a page with the 'Translate (deepl)' option, it's loading forever and no signs of my DeepL budget are used. The option 'Translate (Google)' is just reproducing the original text without translation. The other options are not working either for me. How can this be fixed?

**Comment by sypets** [comment]
@dfpsoeew Have you tried accessing the DeepL API directly with the credentials for your account as described here in the example? Just make sure that works first. https://www.deepl.com/en/docs-api/

It might also help to state your TYPO3 version, PHP version and version of the extension wv_deepltranslate here.

Disclaimer: I am not a maintainer here, just a user of the extension and for us it has been working fine.

**Comment by dfpsoeew** [comment]
TYPO3-Version 11.5.10, PHP-Version 7.4.26, wv_deepltranslate-Version 2.0.1
As you recommended, I tested the DeepL API on my system and it's working. Then I checked if the webserver can issue curl commands by using the code snipped on https://www.php.net/manual/en/curl.examples-basic.php. This also works.

**Comment by calien666** [comment]
@dfpsoeew Is your issue still there in latest version? Please let us know, so we can try to find the problem.

**Comment by calien666** [comment]
After two weeks without response I'll close this issue as done/not longer present. If you think, this is wrong, feel free to open a new issue.
