### ISSUE TITLE
deepl - Update supported api languages

### ISSUE THREAD

**Issue by ayacoo** [web-vision/wv_deepltranslate#63]
- "ID" - Indonesian
- "TR" - Turkish

**Comment by dominikdoerr** [comment]
The supported languages could be fetched from the API endpoint as well and then cached for a certain time.
see: https://www.deepl.com/de/docs-api/other-functions/listing-supported-languages/

**Comment by ayacoo** [comment]
@dominikdoerr  Maybe you can give feedback on the following MR? I use in my extension also the deepl service and possibly we could use the code then also for wv_deepltranslate.

https://github.com/ayacoo/xliff/commit/3e59c8029c5bd2ed1bf9d2e0edfa0f47443136e0
