### ISSUE TITLE
Undefined array key "mode"

### ISSUE THREAD

**Issue by MarkusBausK** [web-vision/wv_deepltranslate#68]
Hi, 

I found this extension and tried to use it the first time. I use TYPO3 11.5.12 with PHP 8.0 on ddev. After installing the extension by composer I added the API key from deepl (from Google I don't want to use). I included Typoscript, languages (DE/EN) are configured and working. The TCA stuff I skipped to test the extension first basically. When I want to translate a page ("create a new translation of this page") I'm getting the following error message only: 

![image](https://user-images.githubusercontent.com/6942617/178121315-a7eeffc9-f6b3-41ae-95c7-c9ba37a08d80.png)

Line 82 means $customMode = $cmdmap['localization']['custom']['mode'];

I can't find anything neither in the docs nor in Typoscript to set something like a "mode". Maybe it's a bug.

Best,
Markus

**Comment by NarkNiro** [comment]
Hello @MarkusBausK ,

Thanks for your report. I will look at this in due time. Or if you like you could also submit a PR for it. :)
