### ISSUE TITLE
Translate Content Element hängt im 3. Schritt von 4

### ISSUE THREAD

**Issue by ceberius** [web-vision/wv_deepltranslate#7]
Servus,

nach der Installation in 10.4.5 und Konfiguration laut Anleitung einschließlich neuem API-Key von Deepl hängt die Übersetzung im 3. Schritt, egal was man auswählt.
Woran kann es liegen?

**Comment by kbenyedder** [comment]
need Fix - LocalizationController 185
        //Bug Fix Typo3 10
        $flatRecords[] = $row;
       return (new JsonResponse())->setPayload([
            'records' => $records,
            'columns' => $this->getPageColumns($pageId,$flatRecords,$params),
        ]);

**Comment by kbenyedder** [comment]
`        //Bug Fix Typo3 10
        $flatRecords[] = $row;
        return (new JsonResponse())->setPayload([
            'records' => $records,
            'columns' => $this->getPageColumns($pageId,$flatRecords,$params),
        ]);
`

**Comment by ceberius** [comment]
thx. worked!

**Comment by dhuettner** [comment]
> ` //Bug Fix Typo3 10 $flatRecords[] = $row; return (new JsonResponse())->setPayload([ 'records' => $records, 'columns' => $this->getPageColumns($pageId,$flatRecords,$params), ]);`

thanks now step 3 and 4 works but no auto translation is generated. The API call is fired but the content is still stored in the default language.

**Comment by NairCoder** [comment]
Fixed in #12 and is in master now. Closing the issue.
Thanks @coding46
