### ISSUE TITLE
Support for content elements with flux?

### ISSUE THREAD

**Issue by DennisMeene** [web-vision/wv_deepltranslate#71]
Your extension works great on TYPO3 v11 with standard content elements, but it seems not to be able to translate content inside flux content elements (https://extensions.typo3.org/extension/flux).

Database-wise this extension adds a field "pi_flexform" which contains the content in an XML-format style:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/78368154/181041328-90698970-e654-47a9-b75e-baa6493dd317.png">

Is there any chance that content like that will be translateable?

**Comment by calien666** [comment]
As flux saves data in flexform and the DataHandler doesn't allow to translate flexforms, this enhancement wouldn't get implemented at this point.
