### ISSUE TITLE
Creating a new glossary entry throws exception because it is assumed default language record with uid=0 exists in sys_language

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#72]
Using branch: glossary-integration with TYPO3 v11

https://github.com/web-vision/wv_deepltranslate/blob/989845a2ecefe5107bbe5e6216828fd09049fed2/Classes/Hooks/DataHandlerHook.php#L62

Exception:

```
Call to a member function getLanguageIsoCode() on null

in /var/www/t3dev.uni-oldenburg.de/htdocs/typo3conf/ext/wv_deepltranslate/Classes/Hooks/DataHandlerHook.php line 63
        $this->languageRepository = $objectManager->get(LanguageRepository::class);

        $systemLanguages = $this->languageRepository->findAll();
        $defaultLanguage = $this->languageRepository->findByUid(0);
        $defaultLangIso = $defaultLanguage->getLanguageIsoCode();

        if ($systemLanguages->count() > 0) {
```

In my current test installation (which is based on the TYPO3 base distribution with introduction package, there is no sys_language record 0. There is no language record for the default language. I am not sure if it is necessary for the default language. 

```
select uid,title from sys_language ;
+-----+--------+
| uid | title  |
+-----+--------+
|   1 | Dansk  |
|   2 | German |
+-----+--------+

```

(You can setup a basic base distribution, see https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/Install.html#install)

```
composer create-project typo3/cms-base-distribution:^11 t3intro11
composer require typo3/cms-introduction:^4.4.1

```

So, not sure how to best handle this, but relying on the record with uid=0 exists in sys_language  - may not always work.

**Comment by sypets** [comment]
There may also be a conceptual problem here because there might be several site configurations with different default languages. See https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/Index.html

**Comment by Riiiad** [comment]
Hey @sypets, thank you for your feedback. We have fixed the issues with the languages. Now we try to fetch always from the site configuration instead of the rootId sysLanguages. 
Here we also found some other unwanted behavior that needs to be fixed. We are making a concept right now, how to implement all changes without rewriting too much of the code at once without proper tests.
