### ISSUE TITLE
503 - urlencode() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by Hobokens** [web-vision/wv_deepltranslate#74]
Deepl 2.2. with glossar function
TYPO3 11.4.14

For example, if I want to translate a news item, I get the error: 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: urlencode() expects parameter 1 to be string, null given | TypeError thrown in file /var/www/vhosts/xxxx.my-provider.de/httpdocs/typo3cms/muster/typo3conf/ext/wv_deepltranslate/Classes/Service/DeeplService.php in line 92. Requested URL: https://www.xxxx.my-provider.de/typo3/record/commit?token=--AnonymizedToken--&redirect=%2Ftypo3%2Frecord%2Fedit%3Ftoken%3D--AnonymizedToken--%26justLocalized%3Dtx_news_domain_model_news%253A263%253A1%26returnUrl%3D%252Ftypo3%252Fmodule%252Fweb%252Flist%253Ftoken%253D121ee25112c632739d925cfc0e69eabb633d4a3a%2526id%253D889%2526table%253Dtx_news_domain_model_news%2526pointer%253D1&cmd%5Btx_news_domain_model_news%5D%5B263%5D%5Blocalize%5D=1&cmd[localization][custom][mode]=deepl `

and a translation does not take place.
The same applies to other extensions (e.g. events2).

The glossary function works without errors and standard texts are translated.

**Comment by Riiiad** [comment]
Will take a look. Thank you for the report.

**Comment by Hobokens** [comment]
Thank you. 
I tested wv_deepltranslate 2.2. also in a TYPO3 version 10.4.31 (PHP 7.4) with the same error message. With version 2.0 there were no problems with translations in extensions (news, events2, jpfaq etc.).

**Comment by Riiiad** [comment]
Bugfix is already on master. Release 2.2.1 will follow soon.
