### ISSUE TITLE
extend form fields for terms

### ISSUE THREAD

**Issue by Hobokens** [web-vision/wv_deepltranslate#77]
Glossary: Often longer terms have to be translated, which are then no longer displayed completely in the BE:

Example: Studien-und Prüfungsordnung für das Lehramt der Musik an Grund-, Mittel-und Realschulen sowie Gymnasien der Hochschule für Musik XXXXX (LASPO)

**Comment by Riiiad** [comment]
Forms have now max widths.  Thank you for your feedback.
