### ISSUE TITLE
Translation process is not completed

### ISSUE THREAD

**Issue by Hobokens** [web-vision/wv_deepltranslate#79]
TYPO 10.4.31, wv_deepltranslate 2.2.1

When translating content elements (e.g. textmedia) on a page, the last step in the processing progress ("`Processing`") is not completed. I have to reload the backend and then see the hidden translated content elements.

When selecting several content elements on  a page only one content element is translated.

When translating extensions (e.g. news, events2), the translation process is completed correctly and the extension is opened so that I can make any necessary corrections directly.

**Comment by Hobokens** [comment]
Here an error message comes, which may be helpful:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function error() on null | Error thrown in file /var/www/vhosts/xxx.my-hosting.de/httpdocs/typo3cms/hfmw/typo3conf/ext/wv_deepltranslate/Classes/Override/CommandMapPostProcessingHook.php in line 49. Requested URL: https://www.my-domain.de/typo3/index.php?route=%%2Fajax%%2Frecords%%2Flocalize&token=--AnonymizedToken--&pageId=1849&srcLanguageId=0&destLanguageId=1&action=localizedeepl&uidList%%5B%%5D=7886&uidList%%5B%%5D=7891&uidList%%5B%%5D=7892 `

**Comment by Hobokens** [comment]
With wv_deepltranslate v.2.0.1 all content elements of a page are translated. (TYPO3 11.5.14)

**Comment by Hobokens** [comment]
Deactivation the container extension (2.0.1). solves the problem.

**Comment by Riiiad** [comment]
Hey @Hobokens,
Thank you for your feedback. Could you give me a more information about your Translation process as I was not able to reproduce the bug. 
Are you using the Containers extension? 
Is the bug in the List or Page view?

**Comment by Hobokens** [comment]
Hey @Riiiad,

I use the extension 'container' (2.0.2). Deactivation the container extension (2.0.1). solves the problem.
The bug also occurs in the list view.
With wv_deepltranslate v.2.0.1 all content elements of a page are translated. (TYPO3 11.5.14)

**Comment by Riiiad** [comment]
@Hobokens Thank you once again for the fast feedback. I was able to reproduce the bug and would update the repository with a fix soon.

**Comment by Hobokens** [comment]
I tested the pull request #80. It solves the problem for me.

**Comment by Riiiad** [comment]
@Hobokens OK that is nice to Hear I already merged to master. So we will also test once more and prepare a release later on this week.

**Comment by rschumachr** [comment]
@Riiiad What's the status on this fix, will it be released soon?

**Comment by calien666** [comment]
After we released new version with the bugfix, this issue can be closed.
