### ISSUE TITLE
Translation process is not completed with start date in content element

### ISSUE THREAD

**Issue by Hobokens** [web-vision/wv_deepltranslate#81]
When a content element has a start date in the future, the translation process is not completed (It's the same behaviour like #79)

**Comment by calien666** [comment]
Will test ins all TYPO3 versions.

- [ ] v9 Testing
- [ ] v10 Testing
- [ ] v11 Testing

**Comment by calien666** [comment]
HI @Hobokens,
I tested in all supported TYPO3 versions and could not detect the issue. Please let me know, if the problem still occurs and make more description about your setup, if so.
Otherwise, if the problem doesn't occur anymore, feel free to close this issue.

Have a nice weekend

**Comment by Hobokens** [comment]
I can't reproduce the error in Version 11.5.24 anymore.
