### ISSUE TITLE
Javascript broken in frontend

### ISSUE THREAD

**Issue by matin73** [web-vision/wv_deepltranslate#83]
If user is logged in in frontend, following javascript is loaded and breaks jquery from default page javascript:

`
<script type="text/javascript">
/*<![CDATA[*/
var require = {"urlArgs":"bust=b5b25fb06fe2265abc41d1aab6beaf2c072c06de","paths":{"jquery":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/\/jquery\/jquery","jquery-ui":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/jquery-ui","datatables":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/jquery.dataTables","nprogress":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/nprogress","moment":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/moment","cropper":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/cropper.min","imagesloaded":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/imagesloaded.pkgd.min","bootstrap":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/bootstrap\/bootstrap","twbs\/bootstrap-datetimepicker":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/bootstrap-datetimepicker","autosize":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/autosize","taboverride":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/taboverride.min","twbs\/bootstrap-slider":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/bootstrap-slider.min","jquery\/autocomplete":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/jquery.autocomplete","d3":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript\/Contrib\/d3\/d3","TYPO3\/CMS\/Core":"\/typo3\/sysext\/core\/Resources\/Public\/JavaScript","TYPO3\/CMS\/Backend":"\/typo3\/sysext\/backend\/Resources\/Public\/JavaScript","TYPO3\/CMS\/WvDeepltranslate":"\/typo3conf\/ext\/wv_deepltranslate\/Resources\/Public\/JavaScript"},"waitSeconds":30,"typo3BaseUrl":"\/?eID=requirejs"}
/*]]>*/
</script>
<script src="typo3/sysext/core/Resources/Public/JavaScript/Contrib/require.js?1639047864" type="text/javascript"></script>
<script src="typo3/sysext/core/Resources/Public/JavaScript/requirejs-loader.js?1639047796" type="text/javascript"></script>

<script type="text/javascript">
/*<![CDATA[*/
/*RequireJS-Module-TYPO3/CMS/WvDeepltranslate/Localization*/
require(["TYPO3/CMS/WvDeepltranslate/Localization"]);

/*]]>*/
</script>`
How can I disable loading js in frontend?

**Comment by matin73** [comment]
found solution myself:
if (TYPO3_MODE === 'BE') {
//override Localization.js
$pageRenderer = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Page\PageRenderer::class);
$pageRenderer->loadRequireJsModule('TYPO3/CMS/WvDeepltranslate/Localization');
}

**Comment by NarkNiro** [comment]
This has already been fixed in version v2.1.0.
