### ISSUE TITLE
 Type Error in GoogleTranslateService

### ISSUE THREAD

**Issue by daniel-stockner** [web-vision/wv_deepltranslate#84]
In the GoogleTranslateService in Line 72 the return type is string. This is wrong an throws an error (_Return value must be of type string, array returned_). 
If the return type is set to array or mixed (the return type of json_decode) it works fine.

**Comment by NarkNiro** [comment]
Thanks for your feedback,

The type error in Google Translate service has been fixed, at the same time Google has been marked as deprecated.
In a few versions, we will remove the complete Google support.
