### ISSUE TITLE
Easier way to delete glossary items

### ISSUE THREAD

**Issue by baschny** [web-vision/wv_deepltranslate#85]
We are testing the glossary functionality in our project (Uni-Osnabrück). Works good, but I found no easy way - as an editor - of deleting a glossary entry.

We allow editors to create `tx_wvdeepltranslate_domain_model_glossaries` which works great when creating new glossary items. This auto-generates DB entries `tx_wvdeepltranslate_domain_model_glossariessync` which are just a json representation of the "translation item" (for the API, I suppose) and are not really manageble manually, since they have an UUID as a title.

I want, as an editor, to be able to delete a glossary term and its translation, by simply removing the `tx_wvdeepltranslate_domain_model_glossaries` entries - and have the API resolve which `tx_wvdeepltranslate_domain_model_glossariessync` entries to delete (or update) on their own.

Any chance of doing having that missing feature included in a future release?

Kind regards,
Ernesto

**Comment by calien666** [comment]
TODO List:

- [ ] Housekeeping
- [ ] Scheduler task
- [ ] DataHandler hook

Ideas: Housekeeping via scheduler or CLI command, which allows to list and cleanup no (longer) synched Glossaries. 
DataHandler hook should take care of deleting and hiding glossaries. In these cases, glossaries should be deleted from DeepL server.

After glossary rework in #148 it would be easy to implement.

**Comment by calien666** [comment]
After refactoring the Glossary functionality with #165 the terms aren't shown anymore. A sync of the glossary only accepts the current active records, as this is normal behaviour. This issue will be done by releasing v3.0
