### ISSUE TITLE
Special character ampersand "&" not decoded

### ISSUE THREAD

**Issue by Idleworks** [web-vision/wv_deepltranslate#86]
Ampersands in headlines or texts (plain texts, no RTE) are not decoded and are stored as "&amp;amp;" in database.

To reproduce:

1. Create an CE with an ampersand character in headline.
2. Translate CE via deepl extension
3. View CE in frontend or in database

![image](https://user-images.githubusercontent.com/6685173/196402014-639fbf6f-046a-4770-93e2-2925c42400d4.png)

Obviously only ampersand character is affacted.

**Comment by calien666** [comment]
Tested on latest master release. Bug appears. We will take a look and fix
