### ISSUE TITLE
Translation for fields with allowLanguageSynchronization not stored in database

### ISSUE THREAD

**Issue by Idleworks** [web-vision/wv_deepltranslate#87]
A field with TCA setting
```
l10n_mode => prefixLangTitle
config => behaviour => allowLanguageSynchronization => 1
```
will not be stored in database because l10n_state is not set to "custom"

TranslationHook should also handle l10n_state for translated fields.

**Comment by calien666** [comment]
For the moment you can also try this solution. I know, it's not best behaviour, but allows you to translate:
https://github.com/web-vision/wv_deepltranslate/issues/115#issuecomment-1435648463
