### ISSUE TITLE
Support for composer-installers-v4

### ISSUE THREAD

**Issue by Patta** [web-vision/wv_deepltranslate#89]
It seems that wv_deepltranslate 2.2.1 is not compatible with the [cms-composer-installers v4](https://github.com/TYPO3/CmsComposerInstallers/releases/tag/v4.0.0-RC1). 

For example, the file deepl-min.css could not be loaded because the legacy directory typo3conf/ext/ did not exist in composer-installers v4. The translation process did not work either.

TYPO3 11.5.17
Composer mode
wv_deepltranslate 2.2.1
typo3/cms-composer-installers ^4.0

**Comment by NarkNiro** [comment]
Thanks for your feedback,
The directory paths for the files have been changed.
