### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by Patta** [web-vision/wv_deepltranslate#90]
Uncaught TypeError: $ is not a function in deepl backend module settings.

![image](https://user-images.githubusercontent.com/2151127/198059764-42c21007-dc4f-45c3-91d2-907d052814ac.png)

TYPO3 11.5.17
Composer mode
wv_deepltranslate 2.2.1
cms-composer-installers ^4.0

**Comment by NarkNiro** [comment]
Thanks for your feedback, 
The inline JavaScript is now done via Settings requireJS Module.
