### ISSUE TITLE
Use local embedded Google Fonts instead of fonts.googleapis.com

### ISSUE THREAD

**Issue by scmika** [web-vision/wv_deepltranslate#91]
Hello everyone,

I've had a customer in Germany on version 1.1.2 who had a problem with Google Fonts being used by requesting the font CSS from fonts.googelapis.com. This plugin is one of two that embeds Google Fonts remotely. The other one was made by a different company specific to that customer, so I can fix that one independently.

I've added a local CSS file to add a locally stored google font and added the default font files format for the family "Share" (eot, svg, ttf, woff, woff2). I've seen it only on the backend layout https://github.com/web-vision/wv_deepltranslate/blob/master/Resources/Private/Layouts/Default.html for the current master version but it should be stored locally anyways. The Resources/Public/Css/googlefonts.css file can provide the required font family "Share". In my release I've even added a hint to the corresponding license file.
```
/**
 All files downloaded from google fonts, respective license is available at ../Fonts/OFL.txt
 */
@font-face {
    font-family: 'Share';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('../Fonts/Share-Regular.eot'); /* IE9 */
    src: url('../Fonts/Share-Regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
    url('../Fonts/Share-Regular.woff2') format('woff2'), /* Modern Browsers */
    url('../Fonts/Share-Regular.woff') format('woff'), /* Modern Browsers */
    url('../Fonts/Share-Regular.ttf') format('truetype'), /* Safari, Android, iOS */
    url('../Fonts/Share-Regular.svg#Share') format('svg'); /* Legacy iOS */
}
```

I'm not sure in how much the "translation.googleapis.com" is an issue in regards to GDPR, but at least the fonts have to be fixed for it. Since the customer still uses an older manually patched version, the fix isn't that urgent.

**Comment by calien666** [comment]
As for the latest master we're no longer including external fonts, I will close this issue.
