### ISSUE TITLE
Too few arguments in makeLocalizationPanel() in TYPO3 v9

### ISSUE THREAD

**Issue by spoonerWeb** [web-vision/wv_deepltranslate#95]
## Issue

```
Too few arguments to function WebVision\WvDeepltranslate\Override\DatabaseRecordList::makeLocalizationPanel(), 2 passed in /var/www/html/public/typo3/sysext/recordlist/Classes/RecordList/DatabaseRecordList.php on line 1528 and exactly 3 expected
```

## Reproduction

1. Setup TYPO3 v9.5
2. Install extension version 2.0.1 or newer
3. Go to list module

Regarding #93 there are code changes in verion 2.0.1 that break every installation with TYPO3 v9.5.
You should remove the support for 9.5 asap.

**Comment by calien666** [comment]
Hi @spoonerWeb,
AFAIK this issue should not appear anymore, as we changed Usage of the DatabaseRecordList according to the installed TYPO3 version. Please check and let me know, if the error is still there. My own testings made no problems, while I refactored the translation butoon behavior (see #134)

**Comment by calien666** [comment]
Fixed with latest master. Class set deprecated and will be removed in future version
