### ISSUE TITLE
Backend translation-switch icon not working in "Production" mode

### ISSUE THREAD

**Issue by baschny** [web-vision/wv_deepltranslate#96]
The `BE/debug` flag influences the functionality of the icon to switch "DeepL Translations" on and off in records (i.e. News Records). It only works with `debug=true`, which is not the case in most production sites.

The issue here seems that the "switch-icon" is loaded via CSS which is minified and merged with `BE/debug=false`, and thus the relative path is not found anymore. Strange that nobody noticed that before?

See:

With this setting (normal "Development/Debug" setting):
```
$GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = true;
```
![deepl-debug-true](https://user-images.githubusercontent.com/337581/207379637-179bb4ab-921f-47e7-a90c-3b418c9c52ef.png)

And with this setting (normal "Production/Live" setting):
```
$GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = false;
```
![deepl-debug-false](https://user-images.githubusercontent.com/337581/207379864-ccf7780f-4297-47e7-821e-cff6f65ca2a4.png)

**Comment by ttg-team-web** [comment]
we also have this issue
thankfully the button still works as expected, even without the icon, but it would be great to have this fixed asap!

**Comment by Hobokens** [comment]
The missing icon is irritating for the editors and generates many questions.
